#!/bin/sh

SERVER_IDS='prod'
INI_FILE="production.ini"
GROUP=deploy
PID_PATH="/var/run/paste"
LOG_PATH="/var/log/paste"
export PYTHONPATH=/var/www/gleebox
export PYTHON_EGG_CACHE=/tmp/.python-eggs
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp

if [ $1 = "start" ]; then

# start all servers
for id in $SERVER_IDS; do
  CMD="paster serve -v --server-name=main --app-name=main --daemon --pid-file=$PID_PATH/gleebox$id.pid --log-file=$LOG_PATH/gleebox$id.log $INI_FILE start server_id=$id"
  echo $CMD
  $CMD
done

else if [ $1 == "stop" ]; then

# stop all servers
for id in $SERVER_IDS; do
  CMD="paster serve --server-name=main --app-name=main --daemon --pid-file=$PID_PATH/gleebox$id.pid --log-file=$LOG_PATH/gleebox$id.log $INI_FILE stop server_id=$id"
  echo $CMD
  $CMD
done

else if [ $1 == "restart" ]; then

# restart all servers
for id in $SERVER_IDS; do
  CMD="paster serve  --server-name=main --app-name=main --daemon --pid-file=$PID_PATH/gleebox$id.pid --log-file=$LOG_PATH/gleebox$id.log $INI_FILE restart server_id=$id"
  echo $CMD
  $CMD
done

else if [ $1 == "status" ]; then

for id in $SERVER_IDS; do
  CMD="paster serve --server-name=main --app-name=main --daemon --pid-file=$PID_PATH/gleebox$id.pid --log-file=$LOG_PATH/gleebox$id.log $INI_FILE status server_id=$id"
  echo $CMD
  $CMD
done

else

echo "Invalid option: $1"

fi
fi
fi
fi


